# Generated by Django 2.1.3 on 2019-01-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_clinic', to='main.Clinic'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doc_clinic', to='main.Clinic'),
        ),
    ]
