# Generated by Django 2.1.3 on 2019-01-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190119_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='contact',
        ),
    ]
