# Generated by Django 2.1.3 on 2019-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190119_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_accepted',
            field=models.IntegerField(default=0),
        ),
    ]
