# Generated by Django 2.1.3 on 2019-01-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_patient_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='avalibility',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fees',
        ),
        migrations.AddField(
            model_name='clinic',
            name='fees',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
